version: "3.9"
services:
  ballot:
    image: local-registry:5002/ballot:latest
    ports:
      - "30040:8080"
  voter:
    image: local-registry:5002/voter:latest
    tty: true
    stdin_open: true
    ports: 
      - "30041:80"
    environment:
      REACT_APP_BALLOT_ENDPOINT:  "${ROOST_CLUSTER_IP}:30040"
      REACT_APP_EC_SERVER_ENDPOINT: "${ROOST_CLUSTER_IP}:30042"
    links:
      - ballot
      - ecserver
  ecserver:
    image: local-registry:5002/ecserver:latest
    ports: 
      - "30042:8081"
  election-commission:
    image: local-registry:5002/ec:latest
    tty: true
    stdin_open: true
    ports: 
      - "30043:80"
    environment:
      REACT_APP_EC_SERVER_ENDPOINT: "${ROOST_CLUSTER_IP}:30042"
    links:
      - ecserver
