// Test generated by RoostGPT for test test1 using AI Model gpt

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"
)

func startServer() {
	fmt.Println("ballot is ready to store votes")
	http.HandleFunc("/", serveRoot)
	http.HandleFunc("/tests/run", runTest)
	fmt.Println(http.ListenAndServe(":8080", nil))
}

func serveRoot(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Welcome to the HomePage!")
}

func runTest(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Running Test!")
}

func TestStartServer(t *testing.T) {
	go startServer()

	// Test serveRoot
	req, err := http.NewRequest("GET", "http://localhost:8080/", nil)
	if err != nil {
		t.Fatal(err)
	}
	res := httptest.NewRecorder()
	handler := http.HandlerFunc(serveRoot)
	handler.ServeHTTP(res, req)
	if status := res.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}

	// Test runTest
	req, err = http.NewRequest("GET", "http://localhost:8080/tests/run", nil)
	if err != nil {
		t.Fatal(err)
	}
	res = httptest.NewRecorder()
	handler = http.HandlerFunc(runTest)
	handler.ServeHTTP(res, req)
	if status := res.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}
}